// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBH_ThuySan.Models;

#nullable disable

namespace QLBH_ThuySan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323031415_AddPartialPaymentFields")]
    partial class AddPartialPaymentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLBH_ThuySan.Models.CauHinhChietKhau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTietLuat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chiTietLuat");

                    b.Property<string>("DoiTuongApDung")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("doiTuongApDung");

                    b.Property<string>("LoaiQuyLuat")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loaiQuyLuat");

                    b.Property<string>("TenCauHinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenCauHinh");

                    b.HasKey("Id")
                        .HasName("PK__CauHinhC__3213E83F12C2C922");

                    b.ToTable("CauHinhChietKhau", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhieu");

                    b.Property<string>("MaHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maHang");

                    b.Property<decimal?>("DonGiaNhap")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("donGiaNhap");

                    b.Property<double?>("SoLuong")
                        .HasColumnType("float")
                        .HasColumnName("soLuong");

                    b.Property<double?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasColumnName("thanhTien")
                        .HasComputedColumnSql("([soLuong]*[donGiaNhap])", false);

                    b.HasKey("MaPhieu", "MaHang")
                        .HasName("PK__ChiTietP__458D7B2C093EF2CD");

                    b.HasIndex("MaHang");

                    b.ToTable("ChiTietPhieuNhap", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.ChiTietPhieuTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maHang");

                    b.Property<string>("MaPhieuTinh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhieuTinh");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("noiDung");

                    b.Property<double?>("SoLuong")
                        .HasColumnType("float")
                        .HasColumnName("soLuong");

                    b.Property<decimal?>("SoTienChietKhau")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("soTienChietKhau");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("thanhTien");

                    b.HasKey("Id")
                        .HasName("PK_ChiTietPhieuTinh");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaPhieuTinh");

                    b.ToTable("ChiTietPhieuTinh", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhieu");

                    b.Property<string>("MaHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maHang");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("giaBan");

                    b.Property<decimal?>("GiaVonTaiThoiDiem")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("giaVonTaiThoiDiem");

                    b.Property<double?>("SoLuong")
                        .HasColumnType("float")
                        .HasColumnName("soLuong");

                    b.Property<double?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasColumnName("thanhTien")
                        .HasComputedColumnSql("([soLuong]*[giaBan])", false);

                    b.HasKey("MaPhieu", "MaHang")
                        .HasName("PK__ChiTietP__458D7B2C6ABCE357");

                    b.HasIndex("MaHang");

                    b.ToTable("ChiTietPhieuXuat", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.ChiTietTon", b =>
                {
                    b.Property<string>("MaKho")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maKho");

                    b.Property<string>("MaHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maHang");

                    b.Property<decimal?>("GiaTriTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("giaTriTon");

                    b.Property<double?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("soLuongTon");

                    b.HasKey("MaKho", "MaHang")
                        .HasName("PK__ChiTietT__2AF7B9E70EBDD425");

                    b.HasIndex("MaHang");

                    b.ToTable("ChiTietTon", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.DaiLy", b =>
                {
                    b.Property<string>("MaDaiLy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maDaiLy");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDisabled");

                    b.Property<string>("LoaiDaiLy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loaiDaiLy");

                    b.Property<string>("TenDaiLy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDaiLy");

                    b.HasKey("MaDaiLy")
                        .HasName("PK__DaiLy__29D3D8D36DED8AAA");

                    b.ToTable("DaiLy", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.DoiTuongChiPhi", b =>
                {
                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maDoiTuong");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDisabled");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDoiTuong");

                    b.HasKey("MaDoiTuong");

                    b.ToTable("DoiTuongChiPhi", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("giaBan");

                    b.Property<string>("MaHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maHang");

                    b.Property<string>("MaHangDonVi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maHangDonVi");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenDonVi");

                    b.Property<int>("TyLeQuyDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("tyLeQuyDoi");

                    b.HasKey("Id")
                        .HasName("PK_DonViTinh");

                    b.HasIndex("MaHang");

                    b.ToTable("DonViTinh", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.HangHoa", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maHang");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("donViTinh");

                    b.Property<decimal?>("GiaBanHienTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("giaBanHienTai");

                    b.Property<decimal?>("GiaVonHienTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("giaVonHienTai");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDisabled");

                    b.Property<string>("QuyCach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quyCach");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenHang");

                    b.HasKey("MaHang")
                        .HasName("PK__HangHoa__C28CA331F1F0035B");

                    b.ToTable("HangHoa", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.KhachHang", b =>
                {
                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maDoiTuong");

                    b.Property<string>("AoNuoi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("aoNuoi");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("diaChi");

                    b.Property<decimal?>("DuNoLuyKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("duNoLuyKe");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDisabled");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenDoiTuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDoiTuong");

                    b.HasKey("MaDoiTuong")
                        .HasName("PK__KhachHan__8B6358B408DF22E4");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.Kho", b =>
                {
                    b.Property<string>("MaKho")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maKho");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDisabled");

                    b.Property<string>("LoaiKho")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loaiKho");

                    b.Property<string>("MaDaiLyPhuTrach")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maDaiLyPhuTrach");

                    b.Property<string>("TenKho")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenKho");

                    b.HasKey("MaKho")
                        .HasName("PK__Kho__26DF73D49E2E612A");

                    b.HasIndex("MaDaiLyPhuTrach");

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.NguoiDung", b =>
                {
                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenNguoiDung");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MatKhau");

                    b.Property<int?>("QuyenNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("QuyenNguoiDung");

                    b.Property<string>("TenHienThi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenHienThi");

                    b.HasKey("TenNguoiDung")
                        .HasName("PK_NguoiDung");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maDoiTuong");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("diaChi");

                    b.Property<decimal?>("DuNoLuyKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("duNoLuyKe");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDisabled");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maSoThue");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("soDienThoai");

                    b.Property<int?>("SoNgayDuocNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soNgayDuocNo");

                    b.Property<string>("TenDoiTuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDoiTuong");

                    b.HasKey("MaDoiTuong")
                        .HasName("PK__NhaCungC__8B6358B489523D70");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhieu");

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("hanThanhToan");

                    b.Property<string>("IdDaiLyNhap")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("idDaiLyNhap");

                    b.Property<string>("IdNhaCungCap")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("idNhaCungCap");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDisabled");

                    b.Property<DateTime?>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayNhap")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayThanhToan");

                    b.Property<decimal?>("SoChuaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soChuaThanhToan");

                    b.Property<decimal?>("SoDaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soDaThanhToan");

                    b.Property<decimal?>("SoPhaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soPhaiThanhToan");

                    b.Property<string>("TrangThaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangthaithanhtoan")
                        .HasDefaultValueSql("(N'Chưa Thanh Toán')");

                    b.HasKey("MaPhieu")
                        .HasName("PK__PhieuNha__49A5B11FB051D1BD");

                    b.HasIndex("IdDaiLyNhap");

                    b.HasIndex("IdNhaCungCap");

                    b.ToTable("PhieuNhap", null, t =>
                        {
                            t.HasTrigger("trg_PhieuNhap_TinhHanThanhToan");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuThuChi", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhieu");

                    b.Property<string>("LoaiPhieu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("loaiPhieu");

                    b.Property<string>("LyDo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("lyDo");

                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maDoiTuong");

                    b.Property<DateTime?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayLap")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("soTien");

                    b.HasKey("MaPhieu")
                        .HasName("PK__PhieuThu__458D7B2C7991D479");

                    b.ToTable("PhieuThuChi", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuTinhChietKhau", b =>
                {
                    b.Property<string>("MaPhieuTinh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhieuTinh");

                    b.Property<DateOnly?>("DenNgay")
                        .HasColumnType("date")
                        .HasColumnName("denNgay");

                    b.Property<string>("LoaiDoiTuong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("loaiDoiTuong");

                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maDoiTuong");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayThanhToan");

                    b.Property<decimal?>("SoChuaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soChuaThanhToan");

                    b.Property<decimal?>("SoDaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soDaThanhToan");

                    b.Property<decimal?>("SoPhaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soPhaiThanhToan");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa thanh toán")
                        .HasColumnName("trangThai");

                    b.Property<DateOnly?>("TuNgay")
                        .HasColumnType("date")
                        .HasColumnName("tuNgay");

                    b.HasKey("MaPhieuTinh")
                        .HasName("PK__PhieuTin__4BED573111C7DFF5");

                    b.ToTable("PhieuTinhChietKhau", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuXuat", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhieu");

                    b.Property<string>("IdDaiLyBan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("idDaiLyBan");

                    b.Property<string>("IdKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("idKhachHang");

                    b.Property<string>("IdNhaCungCap")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("idNhaCungCap");

                    b.Property<string>("LoaiXuat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loaiXuat")
                        .HasDefaultValueSql("('SALES')");

                    b.Property<string>("LyDo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("lyDo");

                    b.Property<string>("MaKhoNhan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maKhoNhan");

                    b.Property<string>("MaKhoXuat")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maKhoXuat");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayThanhToan");

                    b.Property<DateTime?>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayXuat")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("SoChuaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soChuaThanhToan");

                    b.Property<decimal?>("SoDaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soDaThanhToan");

                    b.Property<decimal?>("SoPhaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soPhaiThanhToan");

                    b.Property<string>("TrangThaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangthaithanhtoan")
                        .HasDefaultValueSql("(N'Chưa Thanh Toán')");

                    b.HasKey("MaPhieu")
                        .HasName("PK__PhieuXua__49A5B11FB6FD6FC7");

                    b.HasIndex("IdDaiLyBan");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhaCungCap");

                    b.HasIndex("MaKhoNhan");

                    b.HasIndex("MaKhoXuat");

                    b.ToTable("PhieuXuat", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.SoRiengKhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DienGiai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dienGiai");

                    b.Property<string>("LoaiGiaoDich")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loaiGiaoDich");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maKhachHang");

                    b.Property<DateTime?>("NgayGiaoDich")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayGiaoDich");

                    b.Property<decimal?>("SoTienPhatSinh")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("soTienPhatSinh");

                    b.HasKey("Id")
                        .HasName("PK__SoRiengK__3213E83FD432CDC9");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("SoRiengKhachHang", (string)null);
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.HangHoa", "MaHangNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaHang")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maHan__3EDC53F0");

                    b.HasOne("QLBH_ThuySan.Models.PhieuNhap", "MaPhieuNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maPhi__3DE82FB7");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.ChiTietPhieuTinh", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.HangHoa", "MaHangNavigation")
                        .WithMany()
                        .HasForeignKey("MaHang")
                        .HasConstraintName("FK_ChiTietPhieuTinh_HangHoa");

                    b.HasOne("QLBH_ThuySan.Models.PhieuTinhChietKhau", "MaPhieuTinhNavigation")
                        .WithMany("ChiTietPhieuTinhs")
                        .HasForeignKey("MaPhieuTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ChiTietPhieuTinh_PhieuTinh");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaPhieuTinhNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.HangHoa", "MaHangNavigation")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaHang")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maHan__4865BE2A");

                    b.HasOne("QLBH_ThuySan.Models.PhieuXuat", "MaPhieuNavigation")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maPhi__477199F1");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.ChiTietTon", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.HangHoa", "MaHangNavigation")
                        .WithMany("ChiTietTons")
                        .HasForeignKey("MaHang")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietTo__maHan__3552E9B6");

                    b.HasOne("QLBH_ThuySan.Models.Kho", "MaKhoNavigation")
                        .WithMany("ChiTietTons")
                        .HasForeignKey("MaKho")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietTo__maKho__345EC57D");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaKhoNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.DonViTinh", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.HangHoa", "MaHangNavigation")
                        .WithMany("DonViTinhs")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DonViTinh_HangHoa");

                    b.Navigation("MaHangNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.Kho", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.DaiLy", "MaDaiLyPhuTrachNavigation")
                        .WithMany("Khos")
                        .HasForeignKey("MaDaiLyPhuTrach")
                        .HasConstraintName("FK__Kho__maDaiLyPhuT__2F9A1060");

                    b.Navigation("MaDaiLyPhuTrachNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuNhap", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.DaiLy", "IdDaiLyNhapNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("IdDaiLyNhap")
                        .HasConstraintName("FK__PhieuNhap__idDai__3A179ED3");

                    b.HasOne("QLBH_ThuySan.Models.NhaCungCap", "IdNhaCungCapNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("IdNhaCungCap")
                        .HasConstraintName("FK__PhieuNhap__idNha__3B0BC30C");

                    b.Navigation("IdDaiLyNhapNavigation");

                    b.Navigation("IdNhaCungCapNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuXuat", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.DaiLy", "IdDaiLyBanNavigation")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("IdDaiLyBan")
                        .HasConstraintName("FK__PhieuXuat__idDai__43A1090D");

                    b.HasOne("QLBH_ThuySan.Models.KhachHang", "IdKhachHangNavigation")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("IdKhachHang")
                        .HasConstraintName("FK__PhieuXuat__idKha__44952D46");

                    b.HasOne("QLBH_ThuySan.Models.NhaCungCap", "IdNhaCungCapNavigation")
                        .WithMany()
                        .HasForeignKey("IdNhaCungCap")
                        .HasConstraintName("FK_PhieuXuat_NhaCungCap");

                    b.HasOne("QLBH_ThuySan.Models.Kho", "MaKhoNhanNavigation")
                        .WithMany()
                        .HasForeignKey("MaKhoNhan")
                        .HasConstraintName("FK_PhieuXuat_KhoNhan");

                    b.HasOne("QLBH_ThuySan.Models.Kho", "MaKhoXuatNavigation")
                        .WithMany()
                        .HasForeignKey("MaKhoXuat")
                        .HasConstraintName("FK_PhieuXuat_KhoXuat");

                    b.Navigation("IdDaiLyBanNavigation");

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhaCungCapNavigation");

                    b.Navigation("MaKhoNhanNavigation");

                    b.Navigation("MaKhoXuatNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.SoRiengKhachHang", b =>
                {
                    b.HasOne("QLBH_ThuySan.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("SoRiengKhachHangs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__SoRiengKh__maKha__57A801BA");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.DaiLy", b =>
                {
                    b.Navigation("Khos");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.HangHoa", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("ChiTietPhieuXuats");

                    b.Navigation("ChiTietTons");

                    b.Navigation("DonViTinhs");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.KhachHang", b =>
                {
                    b.Navigation("PhieuXuats");

                    b.Navigation("SoRiengKhachHangs");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.Kho", b =>
                {
                    b.Navigation("ChiTietTons");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuTinhChietKhau", b =>
                {
                    b.Navigation("ChiTietPhieuTinhs");
                });

            modelBuilder.Entity("QLBH_ThuySan.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });
#pragma warning restore 612, 618
        }
    }
}
